# Generated by Django 5.1.5 on 2025-02-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='libraryusers',
            managers=[
            ],
        ),
    ]
