# Generated by Django 5.1.5 on 2025-03-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_profile_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
    ]
