# Generated by Django 5.1.5 on 2025-02-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookish', '0007_book_inventory'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'book')},
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='price',
        ),
    ]
