# Generated by Django 5.1.5 on 2025-02-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cartitems_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='mac_price',
            new_name='max_price',
        ),
    ]
