# Generated by Django 5.1.5 on 2025-02-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
