# Generated by Django 5.1.5 on 2025-02-21 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_remove_coupon_used_by_coupon_users_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
