# Generated by Django 5.1.5 on 2025-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_coupon_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_price',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
