# Generated by Django 5.1.5 on 2025-02-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_coupon_max_price_alter_coupon_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
