# Generated by Django 5.1.5 on 2025-06-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookish', '0009_alter_rating_options_alter_author_name_and_more'),
        ('Orders', '0008_alter_order_subtotal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'book')},
        ),
    ]
