# Generated by Django 5.1.5 on 2025-01-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fiction', 'Fiction'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('History', 'History'), ('Self-Help', 'Self Help'), ('Business', 'Business'), ('Biography', 'Biography')], default='Fiction', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('offers', models.PositiveIntegerField(default=0)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('cover_image', models.ImageField(upload_to='book_cover')),
                ('file', models.FileField(upload_to='book_file')),
                ('authors', models.ManyToManyField(related_name='books', to='Bookish.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Bookish.genre')),
            ],
        ),
    ]
