# Generated by Django 5.1.5 on 2025-01-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookish', '0002_remove_book_file_book_audio_file_book_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Bookish.author'),
            preserve_default=False,
        ),
    ]
