# Generated by Django 5.1.5 on 2025-02-01 06:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookish', '0004_alter_genre_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['id'], name='Bookish_aut_id_f81ace_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-publication_date'], name='Bookish_boo_publica_7bbc95_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='Bookish_com_created_11f753_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['id'], name='Bookish_gen_id_66f6ac_idx'),
        ),
    ]
