# Generated by Django 5.1.5 on 2025-02-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookish', '0005_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
