# Generated by Django 5.1.5 on 2025-06-01 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookish', '0008_bookpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Bookish.book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'very weak'), (2, 'weak'), (3, 'average'), (4, 'good'), (5, 'great')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='Bookish_rat_user_id_56177e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['book'], name='Bookish_rat_book_id_5f325f_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rate'], name='Bookish_rat_rate_0e6ae5_idx'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='Bookish.author'),
        ),
    ]
